#!/usr/bin/env bash
# © 2026 Octávio Filipe Gonçalves
# Callsign: CT7BFV
# License: GNU AGPL-3.0 (https://www.gnu.org/licenses/agpl-3.0.html)
#
# 4ham-spectrum-analysis — Enable APRS (Direwolf) on an existing install
#
# Use this script when you already have 4ham installed and you want to
# add APRS packet decoding via Direwolf KISS TCP without re-running the
# full installer.
#
# What it does:
#   1. Checks if Direwolf is already installed (skips install if so).
#   2. Installs Direwolf via apt (asks for sudo).
#   3. Creates a default direwolf.conf in <project>/config/ if missing.
#   4. Prints clear next-steps to start Direwolf and enable APRS in
#      the 4ham Admin Config panel.
#
# Usage:
#   sudo bash scripts/enable_aprs.sh
#   # or
#   bash scripts/enable_aprs.sh   (will prompt for sudo when needed)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CONF_DIR="$ROOT_DIR/config"
CONF_PATH="$CONF_DIR/direwolf.conf"

# Colours
B="\033[1m"; G="\033[32m"; Y="\033[33m"; R="\033[31m"; C="\033[36m"; N="\033[0m"

run_sudo() {
  if [[ "${EUID}" -eq 0 ]]; then
    "$@"
  else
    sudo "$@"
  fi
}

banner() {
  echo
  echo -e "${B}${C}=====================================================${N}"
  echo -e "${B}${C} 4ham-spectrum-analysis — Enable APRS (Direwolf)${N}"
  echo -e "${B}${C}=====================================================${N}"
  echo
}

check_distro() {
  if [[ ! -f /etc/os-release ]]; then
    echo -e "${R}Error:${N} /etc/os-release not found. This script supports Debian/Ubuntu-based systems." >&2
    exit 1
  fi
  # shellcheck disable=SC1091
  source /etc/os-release
  case "${ID:-}" in
    ubuntu|debian|raspbian|linuxmint|pop|elementary)
      echo -e "Detected distribution: ${G}${PRETTY_NAME:-$ID}${N}"
      ;;
    *)
      echo -e "${Y}Warning:${N} distribution '${ID:-unknown}' is not officially supported."
      echo "         The script will try apt-get anyway."
      ;;
  esac
}

install_direwolf() {
  if command -v direwolf >/dev/null 2>&1; then
    local version
    version="$(direwolf -v 2>&1 | head -n1 || true)"
    echo -e "Direwolf is ${G}already installed${N} (${version})."
    return 0
  fi

  echo -e "${B}Installing Direwolf via apt-get...${N}"
  echo "(you may be prompted for your sudo password)"
  echo
  run_sudo apt-get update
  run_sudo apt-get install -y direwolf

  if ! command -v direwolf >/dev/null 2>&1; then
    echo -e "${R}Error:${N} Direwolf installation failed." >&2
    exit 1
  fi
  echo -e "${G}Direwolf installed successfully.${N}"
}

create_config() {
  if [[ -f "$CONF_PATH" ]]; then
    echo -e "Config already present at ${C}${CONF_PATH}${N} — leaving as is."
    return 0
  fi

  echo -e "Creating default config at ${C}${CONF_PATH}${N}"
  mkdir -p "$CONF_DIR"
  cat > "$CONF_PATH" <<'EOF'
# Direwolf configuration for 4ham-spectrum-analysis (APRS)
# Auto-generated by scripts/enable_aprs.sh — edit MYCALL before transmitting.

MYCALL N0CALL

ADEVICE default null

CHANNEL 0
MODEM 1200

KISSPORT 8001
AGWPORT 0
EOF
  echo -e "${Y}Note:${N} edit ${C}${CONF_PATH}${N} and replace MYCALL N0CALL with your callsign"
  echo "      if you intend to transmit (receive-only does not require it)."
}

print_next_steps() {
  echo
  echo -e "${B}${G}APRS support is now ready.${N}"
  echo
  echo -e "${B}Next steps:${N}"
  echo
  echo -e "  ${B}1.${N} Open the 4ham web interface."
  echo -e "  ${B}2.${N} Reload the page (Ctrl+R / F5)."
  echo -e "  ${B}3.${N} Open ${C}Admin Config${N} → look for the section"
  echo -e "        ${C}APRS Packet Decoding (Direwolf)${N}."
  echo -e "  ${B}4.${N} The badge should now show ${G}\"Direwolf installed\"${N}."
  echo -e "  ${B}5.${N} Tick ${C}\"Enable APRS packet decoding via Direwolf KISS TCP\"${N}"
  echo -e "        and click ${C}\"Save APRS setting\"${N}."
  echo
  echo -e "${B}Notes:${N}"
  echo -e "  • The backend will start Direwolf automatically when APRS is enabled."
  echo -e "  • APRS uses VHF 144.800 MHz (IARU Region 1)."
  echo -e "  • For internet APRS feed (APRS-IS), no extra software is needed —"
  echo -e "    just configure callsign + locator in Admin Config."
  echo
}

main() {
  banner
  check_distro
  install_direwolf
  create_config
  print_next_steps
}

main "$@"
